STARTING_CIRCLE_NUM_POINTS = 500

OUTER_RADIUS = 260
INNER_RADIUS = 100

CUT_THICKNESS = 2.1

LAYER_COUNT = int((OUTER_RADIUS - INNER_RADIUS) // CUT_THICKNESS)

LARGE_THRESHOLD = 10e15
SMALL_THRESHOLD = 10e-15

SMALL_ANGLE_THRESHOLD = 10e-10

STATIC_PLOT = False
STATIC_SPARSE_PLOT = False
SPARSE_STEP = 400