STARTING_CIRCLE_NUM_POINTS = 360

OUTER_RADIUS = 260
INNER_RADIUS = 100

CUT_THICKNESS = 2.1

LAYER_COUNT = int((OUTER_RADIUS - INNER_RADIUS) // CUT_THICKNESS)

LARGE_THRESHOLD = 10e15
SMALL_THRESHOLD = 10e-15